name:                abhijitFP
version:             0.1.0.0
github:              "abhijitmjj/abhijitFP"
license:             BSD3
author:              "Abhijit Gupta"
maintainer:          "abhijit038@gmail.com"
copyright:           "copyright Abhijit Gupta 2021"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Functional Programming in Haskell

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/abhijitmjj/abhijitFP#readme>

dependencies:
- base >= 4.7 && < 5
- random
- containers
- transformers
- regex-tdfa

library:
  source-dirs: src

executables:
  abhijitFP-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - abhijitFP

tests:
  abhijitFP-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - abhijitFP
    - QuickCheck
